---
title: "dsp_device_daily"
author: "XUHENG LI"
date: "2024-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(lubridate)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(caret)
library(e1071)
```


```{r}
dataset <- read_excel("DSP Device Daily (History) Jul21-Jul24-8_14_2024.xlsx")
str(dataset)

```

## data preprocess
```{r}
# transform data type
dataset$`Milk Duration` <- as.numeric(ms(dataset$`Milk Duration`), units = "seconds")
dataset$Date <- as.Date(dataset$Date)

dataset$`Time Milking` <- hm(dataset$`Time Milking`)

# Create a new column to store the time period
dataset$Time_Period <- with(dataset, case_when(
  hour(`Time Milking`) >= 5 & hour(`Time Milking`) < 8 ~ "Early Morning",
  hour(`Time Milking`) >= 8 & hour(`Time Milking`) < 12 ~ "Morning",
  hour(`Time Milking`) >= 12 & hour(`Time Milking`) < 14 ~ "Midday",
  hour(`Time Milking`) >= 14 & hour(`Time Milking`) < 18 ~ "Afternoon",
  hour(`Time Milking`) >= 18 & hour(`Time Milking`) < 22 ~ "Evening",
  TRUE ~ "Night" 
))

# Time segment Example
# Early Morning: 5:00 - 7:59
# Morning: 8:00 - 11:59
# Midday: 12:00 - 13:59
# Afternoon: 14:00 - 17:59
# Evening: 18:00 - 21:59
# Night: 22:00 - 4:59



str(dataset)
summary(dataset)


# calculate NA value
na_rate <- sapply(dataset, function(x) sum(is.na(x)) / length(x) * 100)
na_rate_df <- data.frame(Variable = names(na_rate), NA_Percentage = na_rate)
print(na_rate_df)
```
```{r}
# Observe the overall distribution of the data
par(mfrow = c(1,4))
boxplot(dataset$`Milk Speed Avg.`, main = "Milk Speed Avg.")
boxplot(dataset$`Milk Duration`, main = "Milk Duration")
boxplot(dataset$`Milk Tot.`, main = "Milk Tot.")
boxplot(dataset$`No. of Feed Visits`, main = "No. of Feed Visits")

# Whether it is relevant and whether it is significant
corr = cor(dataset[, c(3,4,7,8)])
p.mat <- cor_pmat(dataset[, c(3,4,7,8)], use = "complete", method = "pearson")
ggcorrplot(corr, hc.order = TRUE, type = "lower", lab = TRUE, p.mat = p.mat, 
    insig = "blank")


# Milk Speed Avg. by Time Period
ggplot(dataset, aes(x = Time_Period, y = `Milk Speed Avg.`)) +
  geom_boxplot(fill = "lightblue") +
  labs(title = "Milk Speed Avg. by Time Period", x = "Time Period", y = "Milk Speed Avg.") +
  theme_minimal()

# Average Milk by Time Period
dataset_avg <- dataset %>%
  group_by(Time_Period) %>%
  summarise(Avg_Milk_Tot = mean(`Milk Tot.`, na.rm = TRUE))
ggplot(dataset_avg, aes(x = Time_Period, y = Avg_Milk_Tot, fill = Time_Period)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::comma) +  
  labs(title = "Average Milk by Time Period", x = "Time Period", y = "Average Milk Total") +
  theme_minimal()


# Milk Speed Avg. vs. Total Milk
ggplot(dataset, aes(x = `Milk Speed Avg.`, y = `Milk Tot.`, color = Time_Period)) +
  geom_point(alpha = 0.7) +
  labs(title = "Milk Speed Avg. vs. Total Milk", x = "Milk Speed Avg.", y = "Total Milk") +
  theme_minimal()


# Feed Visits by Time Period
dataset_summary <- dataset %>%
  group_by(Time_Period) %>%
  summarise(Total_Visits = sum(`No. of Feed Visits`))

ggplot(dataset_summary, aes(x = "", y = Total_Visits, fill = Time_Period)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Feed Visits by Time Period", x = "", y = "") +
  theme_void()


# Total Milk Over Time


ggplot(dataset, aes(x = Date, y = `Milk Tot.`)) +
  geom_line(color = "lightblue") +
  geom_point() +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month") +  
  labs(title = "Total Milk Over Time", x = "Date", y = "Total Milk") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  


ggplot(dataset, aes(x = `No. of Feed Visits`, y = `Milk Tot.`)) +
  geom_point(color = "black", alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "red") + 
  labs(title = "Feed Visits vs Total Milk", 
       x = "Number of Feed Visits", 
       y = "Total Milk") +
  theme_minimal()

```




## modeling

```{r}
df_new <- dataset
df_new$Time_Period <- as.factor(df_new$Time_Period)
model <- lm(`Milk Tot.` ~ `Milk Speed Avg.` + `Milk Duration` + Time_Period + `No. of Feed Visits`, data = df_new)

# LOOCV
train_control_loocv <- trainControl(method = "LOOCV")  
loocv_model <- train(`Milk Tot.` ~ `Milk Speed Avg.` + `Milk Duration` + Time_Period + `No. of Feed Visits`,
                     data = df_new, method = "lm", trControl = train_control_loocv)
print(loocv_model)

```


